# Generated by Django 4.0.5 on 2022-09-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
